/**
 * Semantic icon aliases — prefer these in app code so the underlying glyph can change
 * globally without touching call sites. Spec: docs/ICON_SYSTEM.md §3.
 */
export {
  // Navigation / domain
  LayoutDashboard as DashboardIcon,
  Package as ProductIcon,
  Boxes as ProductsIcon,
  Box as VariantIcon,
  FolderTree as CategoryIcon,
  Tag as BrandIcon,
  Ruler as UnitIcon,
  Warehouse as WarehouseIcon,
  MapPin as LocationIcon,
  ArrowLeftRight as TransferIcon,
  SlidersHorizontal as AdjustmentIcon,
  ClipboardList as CountIcon,
  RotateCw as ReorderIcon,
  BarChart3 as ReportIcon,
  Building2 as SupplierIcon,
  ShoppingCart as PurchaseOrderIcon,
  ShoppingBag as SalesOrderIcon,
  Truck as ShipmentIcon,
  User as UserIcon,
  Users as MembersIcon,
  Bell as NotificationIcon,
  Settings as SettingsIcon,
  Menu as MenuIcon,
  PanelLeft as PanelLeftIcon,
  Sun as SunIcon,
  Moon as MoonIcon,
  Component as ComponentIcon,
  Calendar as CalendarIcon,
  File as FileIcon,
  CloudUpload as UploadCloudIcon,
  Image as ImageIcon,
  // Actions
  Plus as AddIcon,
  Pencil as EditIcon,
  Trash2 as DeleteIcon,
  Download as ExportIcon,
  Upload as ImportIcon,
  Filter as FilterIcon,
  Search as SearchIcon,
  X as XIcon,
  Ellipsis as MoreIcon,
  ChevronDown as ChevronDownIcon,
  ChevronUp as ChevronUpIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  ChevronsLeft as ChevronsLeftIcon,
  ChevronsRight as ChevronsRightIcon,
  ChevronsUpDown as ChevronsUpDownIcon,
  // Status
  CircleCheck as SuccessIcon,
  TriangleAlert as WarningIcon,
  CircleX as ErrorIcon,
  Info as InfoIcon,
} from 'lucide-react';
